source 'https://rubygems.org'

gem 'rails', '~> 5.2.0'
gem 'pg', '~> 1.1.3'
gem 'puma', '~> 3.12'
gem 'sass-rails', '~> 5.0.7'
gem 'uglifier', '~> 4.1.19'

gem 'jquery-rails', '~> 4.3.1'
gem 'bootstrap-sass', '~> 3.3.7'

gem 'slim', '~> 4.0.1'
gem 'slim-rails', '~> 3.2.0'

gem 'simple_form', '~> 4.0.1'
gem 'carrierwave'
#{skip_theme ? '' : "gem 'bootstrap_sb_admin_base_v2', '~> 0.3.3'"}

# Authentication && Authorization
gem 'devise', '~> 4.5.0'
gem 'pundit', '~> 2.0.0'

#gem 'omniauth-oauth2', '~> 1.5.0'
#gem 'omniauth-facebook', '~> 5.0.0'
#gem 'omniauth-linkedin', '~> 0.2.0'
#gem 'omniauth-twitter', '~> 1.4.0'
#gem 'omniauth-google-oauth2', '~> 0.5.3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~>  1.3.2', require: false

source 'https://rails-assets.org' do
  gem 'rails-assets-airbrake-js-client', '~> 0.9'
end

group :staging, :production do
  gem 'airbrake', '~> 6.2.0'
end

group :staging, :development do
  gem 'safety_mailer', '~> 0.0.10'
end

group :development do
  gem 'annotate', '~> 2.7.4'
  gem 'capistrano', '~> %{capistrano_version}'
  gem 'capistrano-bundler', '~> 1.3', require: false
  gem 'capistrano-passenger', '~> 0.2.0', require: false
  gem 'capistrano-rails', '~> 1.4.0', require: false
  gem 'capistrano-rvm', '~> 0.1.2', require: false
  gem 'capistrano-the-best-compression', github: 'SumatoSoft/capistrano-the-best-compression'
  gem 'letter_opener', '~> 1.6.0'
  gem 'listen', '~> 3.1.5'
  gem 'rubocop', '~> 0.59.2', require: false
end

group :development, :test do
  gem 'pry', '~> 0.10.4'
end

group :test do
  gem 'factory_bot_rails', '~> 4.11.1'
end
